language: cpp
cache:
  apt: true
  directories:
    - $HOME/Library/Caches/Homebrew
os:
  # - linux
  - osx
sudo: required
dist: xenial
addons:
  apt:
    packages:
      - build-essential
      - cmake
      - g++
      - clang
      - libboost-chrono-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-thread-dev
      - libminiupnpc-dev
      - libssl-dev
compiler:
  - g++
  - clang++
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libressl miniupnpc && brew upgrade boost ; fi
env:
  matrix:
    - BUILD_TYPE=Release UPNP=ON
    - BUILD_TYPE=Release UPNP=OFF
  exclude:
    - os: osx
      compiler: g++
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd build && cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DWITH_UPNP=${UPNP} && make ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then make HOMEBREW=1 USE_UPNP=${UPNP} ; fi
